### ISSUE TITLE
Command pipeline

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-shell#15]
should reuse eventbus for exchanging objects or at least the eventbus codecs to encode / decode objects to/from buffer/string

**Comment by micocube** [comment]
Hello,My idol，This project is great, I‘m using it, but i really want it to support the pipeline, i want to ask when will it be available,thanks.

**Comment by vietj** [comment]
this project does not get anymore contributions, due to lack of
contributors, so it is not planned.

**Comment by vietj** [comment]
I'm adding the help-wanted label, to make it clear that it can be contributed to.
