### ISSUE TITLE
verticle-deploy with options

### ISSUE THREAD

**Issue by qsys** [vert-x3/vertx-shell#17]
more like a feature request: command 'verticle-deploy' doesn't come with the possibility to add deployment options. If a second argument (json-string?) is given, a verticle with deployment options could be deployed from the shell (which would be nice, since verticles without any config/options are pretty rare)

**Comment by vietj** [comment]
+1

**Comment by EmadAlblueshi** [comment]
@vietj kindly see [#29](https://github.com/vert-x3/vertx-shell/pull/29)

**Comment by vietj** [comment]
@EmadAlblueshi thanks for the contribution!
