### ISSUE TITLE
non-interactive SSH run

### ISSUE THREAD

**Issue by abcfy2** [vert-x3/vertx-shell#19]
I've set vertx-shell to connect with SSH, and everything works very well.

The only problem is, how to do non-interactive things vis ``ssh`` command?

I've tried:

    ssh user@${ip} -p ${port} ls

But I failed.

**Comment by vietj** [comment]
it is currently not implemented.

**Comment by abcfy2** [comment]
I use ``expect`` instead.

```expect
#!expect -f
spawn ssh -o StrictHostKeyChecking=no user@${ip} -p ${port}
expect "Password: "
send "PASSWORD\r"
expect "% "
send "ls\r"
expect "% "
send "exit\r"
expect eof
```

Hope it will be simplified by using ``ssh`` non-interactive.

**Comment by vietj** [comment]
yes it should be supported, I agree with you. thanks for the workaround.

**Comment by vietj** [comment]
I've made it an enhancement
