### ISSUE TITLE
Does vertx-shell support vi command?

### ISSUE THREAD

**Issue by wcc526** [vert-x3/vertx-shell#21]
Does vertx-shell support vi command?

when I ssh to the vertx-shell, Can I use the h+i+j+k to move the cursor?

**Comment by vietj** [comment]
Do you mean wether the shell prompt supports VI mode (as opposed to emacs mode) ?

**Comment by wcc526** [comment]
yes.
Does the shell prompt supports vi MODE?

**Comment by vietj** [comment]
no it does not support, the focus has been on supporting emacs mode with the most useful key bindings.

**Comment by wcc526** [comment]
How can I modify the key bindings for the vi MODE?

**Comment by vietj** [comment]
the problem is that the readline implementation does not implement the binding for vi mode.

**Comment by wcc526** [comment]
The problem is the io.termd.core.readline this module not support vi mode ?

I want to implement the vi mode shell base on the vertx-shell,which code file I should modify?

**Comment by vietj** [comment]
yes it should be supported in Termd project.

**Comment by vietj** [comment]
it would be a useful contribution to Termd, if I were you I would start by adding binding to switch from emacs to vi .

**Comment by wcc526** [comment]
OK,Thank you!
