### ISSUE TITLE
Bump Netty version version to 4.1 

### ISSUE THREAD

**Issue by keaplogik** [vert-x3/vertx-shell#22]
At some point it would be nice to get a bump on the netty version. I'm assuming you are dependant on termd's netty version though based on reviewing your pom. Is this something that could be possible.

We have been trying to work with Netflix ribbon and specifically RxNetty which are moving to newer versions of netty that conflict at runtime.

**Comment by keaplogik** [comment]
This request likely goes under core.

**Comment by vietj** [comment]
there is an http2 branch in vertx core that has updated the version to 4.1 .

Vert.x 3.3 will likely uses Netty 4.1

**Comment by keaplogik** [comment]
Thanks for the heads up
