### ISSUE TITLE
Update SSH to Property File Auth Provider

### ISSUE THREAD

**Issue by fabiankirstein** [vert-x3/vertx-shell#49]
#### Describe the feature

The Shiro authentication is deprecated and is is recommend to use the property file auth provider (https://vertx.io/docs/vertx-auth-properties/java/). The implementation and documentation of the Vertx shell should reflect this. 

#### Use cases

Use the property file auth provider to define users for the SSH shll

#### Contribution

There seems to be an open pull request already: https://github.com/vert-x3/vertx-shell/pull/45

**Comment by vietj** [comment]
thanks, we should rebase this PR

**Comment by fabiankirstein** [comment]
Thanks a lot for solving this. However, I just tried it but I get the follow error:

`io.vertx.core.impl.NoStackTraceThrowable: Provider not found [properties] / check your classpath`

I added to my POM:
```
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-auth-properties</artifactId>
</dependency>
```

I followed the instructions here: https://vertx.io/docs/vertx-shell/java. My code looks like in the documentation:

```java
ShellService service = ShellService.create(vertx,
  new ShellServiceOptions().setSSHOptions(
    new SSHTermOptions().
      setHost("localhost").
      setPort(5000).
      setKeyPairOptions(new JksOptions().
        setPath("server-keystore.jks").
        setPassword("wibble")
      ).
      setAuthOptions(
        new JsonObject()
          .put("provider", "properties")
          .put("type", "PROPERTIES")
          .put("config", new JsonObject().
            put("properties_path", "file:/path/to/my/auth.properties"))
      )
  )
);
service.start();
```

Do I need to do something more? 
Thanks.
